// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package remotepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RemoteServiceClient is the client API for RemoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteServiceClient interface {
	SubmitCode(ctx context.Context, in *SubmitCodeRequest, opts ...grpc.CallOption) (*SubmitCodeResponse, error)
	CrawlProblem(ctx context.Context, in *CrawlProblemRequest, opts ...grpc.CallOption) (*CrawlProblemResponse, error)
	QueryCrawlResult(ctx context.Context, in *QueryCrawlResultRequest, opts ...grpc.CallOption) (*QueryCrawlResultResponse, error)
}

type remoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteServiceClient(cc grpc.ClientConnInterface) RemoteServiceClient {
	return &remoteServiceClient{cc}
}

func (c *remoteServiceClient) SubmitCode(ctx context.Context, in *SubmitCodeRequest, opts ...grpc.CallOption) (*SubmitCodeResponse, error) {
	out := new(SubmitCodeResponse)
	err := c.cc.Invoke(ctx, "/RemoteService/SubmitCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) CrawlProblem(ctx context.Context, in *CrawlProblemRequest, opts ...grpc.CallOption) (*CrawlProblemResponse, error) {
	out := new(CrawlProblemResponse)
	err := c.cc.Invoke(ctx, "/RemoteService/CrawlProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) QueryCrawlResult(ctx context.Context, in *QueryCrawlResultRequest, opts ...grpc.CallOption) (*QueryCrawlResultResponse, error) {
	out := new(QueryCrawlResultResponse)
	err := c.cc.Invoke(ctx, "/RemoteService/QueryCrawlResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteServiceServer is the server API for RemoteService service.
// All implementations must embed UnimplementedRemoteServiceServer
// for forward compatibility
type RemoteServiceServer interface {
	SubmitCode(context.Context, *SubmitCodeRequest) (*SubmitCodeResponse, error)
	CrawlProblem(context.Context, *CrawlProblemRequest) (*CrawlProblemResponse, error)
	QueryCrawlResult(context.Context, *QueryCrawlResultRequest) (*QueryCrawlResultResponse, error)
	mustEmbedUnimplementedRemoteServiceServer()
}

// UnimplementedRemoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRemoteServiceServer struct {
}

func (UnimplementedRemoteServiceServer) SubmitCode(context.Context, *SubmitCodeRequest) (*SubmitCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCode not implemented")
}
func (UnimplementedRemoteServiceServer) CrawlProblem(context.Context, *CrawlProblemRequest) (*CrawlProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlProblem not implemented")
}
func (UnimplementedRemoteServiceServer) QueryCrawlResult(context.Context, *QueryCrawlResultRequest) (*QueryCrawlResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCrawlResult not implemented")
}
func (UnimplementedRemoteServiceServer) mustEmbedUnimplementedRemoteServiceServer() {}

// UnsafeRemoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteServiceServer will
// result in compilation errors.
type UnsafeRemoteServiceServer interface {
	mustEmbedUnimplementedRemoteServiceServer()
}

func RegisterRemoteServiceServer(s grpc.ServiceRegistrar, srv RemoteServiceServer) {
	s.RegisterService(&_RemoteService_serviceDesc, srv)
}

func _RemoteService_SubmitCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).SubmitCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteService/SubmitCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).SubmitCode(ctx, req.(*SubmitCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_CrawlProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).CrawlProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteService/CrawlProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).CrawlProblem(ctx, req.(*CrawlProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_QueryCrawlResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCrawlResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).QueryCrawlResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RemoteService/QueryCrawlResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).QueryCrawlResult(ctx, req.(*QueryCrawlResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RemoteService",
	HandlerType: (*RemoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCode",
			Handler:    _RemoteService_SubmitCode_Handler,
		},
		{
			MethodName: "CrawlProblem",
			Handler:    _RemoteService_CrawlProblem_Handler,
		},
		{
			MethodName: "QueryCrawlResult",
			Handler:    _RemoteService_QueryCrawlResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remotepb/service.proto",
}
