// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: problempb/contest_problem.proto

package problempb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ContestProblem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContestId    uint64 `protobuf:"varint,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	ProblemId    uint64 `protobuf:"varint,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ProblemOrder string `protobuf:"bytes,3,opt,name=problem_order,json=problemOrder,proto3" json:"problem_order,omitempty"`
	Title        string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Submitted    uint64 `protobuf:"varint,5,opt,name=submitted,proto3" json:"submitted,omitempty"`
	Accepted     uint64 `protobuf:"varint,6,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *ContestProblem) Reset() {
	*x = ContestProblem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_problempb_contest_problem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContestProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestProblem) ProtoMessage() {}

func (x *ContestProblem) ProtoReflect() protoreflect.Message {
	mi := &file_problempb_contest_problem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestProblem.ProtoReflect.Descriptor instead.
func (*ContestProblem) Descriptor() ([]byte, []int) {
	return file_problempb_contest_problem_proto_rawDescGZIP(), []int{0}
}

func (x *ContestProblem) GetContestId() uint64 {
	if x != nil {
		return x.ContestId
	}
	return 0
}

func (x *ContestProblem) GetProblemId() uint64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *ContestProblem) GetProblemOrder() string {
	if x != nil {
		return x.ProblemOrder
	}
	return ""
}

func (x *ContestProblem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContestProblem) GetSubmitted() uint64 {
	if x != nil {
		return x.Submitted
	}
	return 0
}

func (x *ContestProblem) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_problempb_contest_problem_proto protoreflect.FileDescriptor

var file_problempb_contest_problem_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x73, 0x64, 0x6b, 0x22, 0xc3, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x63, 0x6e, 0x75, 0x76,
	0x6a, 0x2f, 0x76, 0x68, 0x6f, 0x6a, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_problempb_contest_problem_proto_rawDescOnce sync.Once
	file_problempb_contest_problem_proto_rawDescData = file_problempb_contest_problem_proto_rawDesc
)

func file_problempb_contest_problem_proto_rawDescGZIP() []byte {
	file_problempb_contest_problem_proto_rawDescOnce.Do(func() {
		file_problempb_contest_problem_proto_rawDescData = protoimpl.X.CompressGZIP(file_problempb_contest_problem_proto_rawDescData)
	})
	return file_problempb_contest_problem_proto_rawDescData
}

var file_problempb_contest_problem_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_problempb_contest_problem_proto_goTypes = []interface{}{
	(*ContestProblem)(nil), // 0: sdk.ContestProblem
}
var file_problempb_contest_problem_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_problempb_contest_problem_proto_init() }
func file_problempb_contest_problem_proto_init() {
	if File_problempb_contest_problem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_problempb_contest_problem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContestProblem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_problempb_contest_problem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_problempb_contest_problem_proto_goTypes,
		DependencyIndexes: file_problempb_contest_problem_proto_depIdxs,
		MessageInfos:      file_problempb_contest_problem_proto_msgTypes,
	}.Build()
	File_problempb_contest_problem_proto = out.File
	file_problempb_contest_problem_proto_rawDesc = nil
	file_problempb_contest_problem_proto_goTypes = nil
	file_problempb_contest_problem_proto_depIdxs = nil
}
