// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package problempb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ProblemServiceClient is the client API for ProblemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProblemServiceClient interface {
	ListProblems(ctx context.Context, in *ListProblemsRequest, opts ...grpc.CallOption) (*ListProblemsResponse, error)
	GetProblemById(ctx context.Context, in *GetProblemByIdRequest, opts ...grpc.CallOption) (*GetProblemByIdResponse, error)
	SearchProblemByCondition(ctx context.Context, in *SearchProblemByConditionRequest, opts ...grpc.CallOption) (*SearchProblemByConditionResponse, error)
	CreateContest(ctx context.Context, in *CreateContestRequest, opts ...grpc.CallOption) (*CreateContestResponse, error)
	ListContests(ctx context.Context, in *ListContestsRequest, opts ...grpc.CallOption) (*ListContestsResponse, error)
	SearchContestByCondition(ctx context.Context, in *SearchContestByConditionRequest, opts ...grpc.CallOption) (*SearchContestByConditionResponse, error)
	GetContestById(ctx context.Context, in *GetContestByIdRequest, opts ...grpc.CallOption) (*GetContestByIdResponse, error)
	AddContestParticipant(ctx context.Context, in *AddContestParticipantRequest, opts ...grpc.CallOption) (*AddContestParticipantResponse, error)
	GenerateContestParticipants(ctx context.Context, in *GenerateContestParticipantsRequest, opts ...grpc.CallOption) (*GenerateContestParticipantsResponse, error)
	AddContestAdmin(ctx context.Context, in *AddContestAdminRequest, opts ...grpc.CallOption) (*AddContestAdminResponse, error)
	GetContestAdmins(ctx context.Context, in *GetContestAdminsRequest, opts ...grpc.CallOption) (*GetContestAdminsResponse, error)
	GetContestParticipants(ctx context.Context, in *GetContestParticipantsRequest, opts ...grpc.CallOption) (*GetContestParticipantsResponse, error)
	AddContestProblem(ctx context.Context, in *AddContestProblemRequest, opts ...grpc.CallOption) (*AddContestProblemResponse, error)
	DeleteContestProblem(ctx context.Context, in *DeleteContestProblemRequest, opts ...grpc.CallOption) (*DeleteContestProblemResponse, error)
	DeleteContestAdmin(ctx context.Context, in *DeleteContestAdminRequest, opts ...grpc.CallOption) (*DeleteContestAdminResponse, error)
	UpdateContest(ctx context.Context, in *UpdateContestRequest, opts ...grpc.CallOption) (*UpdateContestResponse, error)
	UpdateContestProblems(ctx context.Context, in *UpdateContestProblemsRequest, opts ...grpc.CallOption) (*UpdateContestProblemsResponse, error)
	GetContestProblems(ctx context.Context, in *GetContestProblemsRequest, opts ...grpc.CallOption) (*GetContestProblemsResponse, error)
	GetUserContests(ctx context.Context, in *GetUserContestsRequest, opts ...grpc.CallOption) (*GetUserContestsResponse, error)
	RandProblem(ctx context.Context, in *RandProblemRequest, opts ...grpc.CallOption) (*RandProblemResponse, error)
	RawProblemList(ctx context.Context, in *RawProblemListRequest, opts ...grpc.CallOption) (*RawProblemListResponse, error)
	UpdateProblemGroup(ctx context.Context, in *UpdateProblemGroupRequest, opts ...grpc.CallOption) (*UpdateProblemGroupResponse, error)
}

type problemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProblemServiceClient(cc grpc.ClientConnInterface) ProblemServiceClient {
	return &problemServiceClient{cc}
}

func (c *problemServiceClient) ListProblems(ctx context.Context, in *ListProblemsRequest, opts ...grpc.CallOption) (*ListProblemsResponse, error) {
	out := new(ListProblemsResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/ListProblems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetProblemById(ctx context.Context, in *GetProblemByIdRequest, opts ...grpc.CallOption) (*GetProblemByIdResponse, error) {
	out := new(GetProblemByIdResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/GetProblemById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) SearchProblemByCondition(ctx context.Context, in *SearchProblemByConditionRequest, opts ...grpc.CallOption) (*SearchProblemByConditionResponse, error) {
	out := new(SearchProblemByConditionResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/SearchProblemByCondition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) CreateContest(ctx context.Context, in *CreateContestRequest, opts ...grpc.CallOption) (*CreateContestResponse, error) {
	out := new(CreateContestResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/CreateContest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) ListContests(ctx context.Context, in *ListContestsRequest, opts ...grpc.CallOption) (*ListContestsResponse, error) {
	out := new(ListContestsResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/ListContests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) SearchContestByCondition(ctx context.Context, in *SearchContestByConditionRequest, opts ...grpc.CallOption) (*SearchContestByConditionResponse, error) {
	out := new(SearchContestByConditionResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/SearchContestByCondition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetContestById(ctx context.Context, in *GetContestByIdRequest, opts ...grpc.CallOption) (*GetContestByIdResponse, error) {
	out := new(GetContestByIdResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/GetContestById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) AddContestParticipant(ctx context.Context, in *AddContestParticipantRequest, opts ...grpc.CallOption) (*AddContestParticipantResponse, error) {
	out := new(AddContestParticipantResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/AddContestParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GenerateContestParticipants(ctx context.Context, in *GenerateContestParticipantsRequest, opts ...grpc.CallOption) (*GenerateContestParticipantsResponse, error) {
	out := new(GenerateContestParticipantsResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/GenerateContestParticipants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) AddContestAdmin(ctx context.Context, in *AddContestAdminRequest, opts ...grpc.CallOption) (*AddContestAdminResponse, error) {
	out := new(AddContestAdminResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/AddContestAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetContestAdmins(ctx context.Context, in *GetContestAdminsRequest, opts ...grpc.CallOption) (*GetContestAdminsResponse, error) {
	out := new(GetContestAdminsResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/GetContestAdmins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetContestParticipants(ctx context.Context, in *GetContestParticipantsRequest, opts ...grpc.CallOption) (*GetContestParticipantsResponse, error) {
	out := new(GetContestParticipantsResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/GetContestParticipants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) AddContestProblem(ctx context.Context, in *AddContestProblemRequest, opts ...grpc.CallOption) (*AddContestProblemResponse, error) {
	out := new(AddContestProblemResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/AddContestProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) DeleteContestProblem(ctx context.Context, in *DeleteContestProblemRequest, opts ...grpc.CallOption) (*DeleteContestProblemResponse, error) {
	out := new(DeleteContestProblemResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/DeleteContestProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) DeleteContestAdmin(ctx context.Context, in *DeleteContestAdminRequest, opts ...grpc.CallOption) (*DeleteContestAdminResponse, error) {
	out := new(DeleteContestAdminResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/DeleteContestAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) UpdateContest(ctx context.Context, in *UpdateContestRequest, opts ...grpc.CallOption) (*UpdateContestResponse, error) {
	out := new(UpdateContestResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/UpdateContest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) UpdateContestProblems(ctx context.Context, in *UpdateContestProblemsRequest, opts ...grpc.CallOption) (*UpdateContestProblemsResponse, error) {
	out := new(UpdateContestProblemsResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/UpdateContestProblems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetContestProblems(ctx context.Context, in *GetContestProblemsRequest, opts ...grpc.CallOption) (*GetContestProblemsResponse, error) {
	out := new(GetContestProblemsResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/GetContestProblems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetUserContests(ctx context.Context, in *GetUserContestsRequest, opts ...grpc.CallOption) (*GetUserContestsResponse, error) {
	out := new(GetUserContestsResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/GetUserContests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) RandProblem(ctx context.Context, in *RandProblemRequest, opts ...grpc.CallOption) (*RandProblemResponse, error) {
	out := new(RandProblemResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/RandProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) RawProblemList(ctx context.Context, in *RawProblemListRequest, opts ...grpc.CallOption) (*RawProblemListResponse, error) {
	out := new(RawProblemListResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/RawProblemList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) UpdateProblemGroup(ctx context.Context, in *UpdateProblemGroupRequest, opts ...grpc.CallOption) (*UpdateProblemGroupResponse, error) {
	out := new(UpdateProblemGroupResponse)
	err := c.cc.Invoke(ctx, "/sdk.ProblemService/UpdateProblemGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProblemServiceServer is the server API for ProblemService service.
// All implementations must embed UnimplementedProblemServiceServer
// for forward compatibility
type ProblemServiceServer interface {
	ListProblems(context.Context, *ListProblemsRequest) (*ListProblemsResponse, error)
	GetProblemById(context.Context, *GetProblemByIdRequest) (*GetProblemByIdResponse, error)
	SearchProblemByCondition(context.Context, *SearchProblemByConditionRequest) (*SearchProblemByConditionResponse, error)
	CreateContest(context.Context, *CreateContestRequest) (*CreateContestResponse, error)
	ListContests(context.Context, *ListContestsRequest) (*ListContestsResponse, error)
	SearchContestByCondition(context.Context, *SearchContestByConditionRequest) (*SearchContestByConditionResponse, error)
	GetContestById(context.Context, *GetContestByIdRequest) (*GetContestByIdResponse, error)
	AddContestParticipant(context.Context, *AddContestParticipantRequest) (*AddContestParticipantResponse, error)
	GenerateContestParticipants(context.Context, *GenerateContestParticipantsRequest) (*GenerateContestParticipantsResponse, error)
	AddContestAdmin(context.Context, *AddContestAdminRequest) (*AddContestAdminResponse, error)
	GetContestAdmins(context.Context, *GetContestAdminsRequest) (*GetContestAdminsResponse, error)
	GetContestParticipants(context.Context, *GetContestParticipantsRequest) (*GetContestParticipantsResponse, error)
	AddContestProblem(context.Context, *AddContestProblemRequest) (*AddContestProblemResponse, error)
	DeleteContestProblem(context.Context, *DeleteContestProblemRequest) (*DeleteContestProblemResponse, error)
	DeleteContestAdmin(context.Context, *DeleteContestAdminRequest) (*DeleteContestAdminResponse, error)
	UpdateContest(context.Context, *UpdateContestRequest) (*UpdateContestResponse, error)
	UpdateContestProblems(context.Context, *UpdateContestProblemsRequest) (*UpdateContestProblemsResponse, error)
	GetContestProblems(context.Context, *GetContestProblemsRequest) (*GetContestProblemsResponse, error)
	GetUserContests(context.Context, *GetUserContestsRequest) (*GetUserContestsResponse, error)
	RandProblem(context.Context, *RandProblemRequest) (*RandProblemResponse, error)
	RawProblemList(context.Context, *RawProblemListRequest) (*RawProblemListResponse, error)
	UpdateProblemGroup(context.Context, *UpdateProblemGroupRequest) (*UpdateProblemGroupResponse, error)
	mustEmbedUnimplementedProblemServiceServer()
}

// UnimplementedProblemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProblemServiceServer struct {
}

func (UnimplementedProblemServiceServer) ListProblems(context.Context, *ListProblemsRequest) (*ListProblemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProblems not implemented")
}
func (UnimplementedProblemServiceServer) GetProblemById(context.Context, *GetProblemByIdRequest) (*GetProblemByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblemById not implemented")
}
func (UnimplementedProblemServiceServer) SearchProblemByCondition(context.Context, *SearchProblemByConditionRequest) (*SearchProblemByConditionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProblemByCondition not implemented")
}
func (UnimplementedProblemServiceServer) CreateContest(context.Context, *CreateContestRequest) (*CreateContestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContest not implemented")
}
func (UnimplementedProblemServiceServer) ListContests(context.Context, *ListContestsRequest) (*ListContestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContests not implemented")
}
func (UnimplementedProblemServiceServer) SearchContestByCondition(context.Context, *SearchContestByConditionRequest) (*SearchContestByConditionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchContestByCondition not implemented")
}
func (UnimplementedProblemServiceServer) GetContestById(context.Context, *GetContestByIdRequest) (*GetContestByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContestById not implemented")
}
func (UnimplementedProblemServiceServer) AddContestParticipant(context.Context, *AddContestParticipantRequest) (*AddContestParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContestParticipant not implemented")
}
func (UnimplementedProblemServiceServer) GenerateContestParticipants(context.Context, *GenerateContestParticipantsRequest) (*GenerateContestParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateContestParticipants not implemented")
}
func (UnimplementedProblemServiceServer) AddContestAdmin(context.Context, *AddContestAdminRequest) (*AddContestAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContestAdmin not implemented")
}
func (UnimplementedProblemServiceServer) GetContestAdmins(context.Context, *GetContestAdminsRequest) (*GetContestAdminsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContestAdmins not implemented")
}
func (UnimplementedProblemServiceServer) GetContestParticipants(context.Context, *GetContestParticipantsRequest) (*GetContestParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContestParticipants not implemented")
}
func (UnimplementedProblemServiceServer) AddContestProblem(context.Context, *AddContestProblemRequest) (*AddContestProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContestProblem not implemented")
}
func (UnimplementedProblemServiceServer) DeleteContestProblem(context.Context, *DeleteContestProblemRequest) (*DeleteContestProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContestProblem not implemented")
}
func (UnimplementedProblemServiceServer) DeleteContestAdmin(context.Context, *DeleteContestAdminRequest) (*DeleteContestAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContestAdmin not implemented")
}
func (UnimplementedProblemServiceServer) UpdateContest(context.Context, *UpdateContestRequest) (*UpdateContestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContest not implemented")
}
func (UnimplementedProblemServiceServer) UpdateContestProblems(context.Context, *UpdateContestProblemsRequest) (*UpdateContestProblemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContestProblems not implemented")
}
func (UnimplementedProblemServiceServer) GetContestProblems(context.Context, *GetContestProblemsRequest) (*GetContestProblemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContestProblems not implemented")
}
func (UnimplementedProblemServiceServer) GetUserContests(context.Context, *GetUserContestsRequest) (*GetUserContestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserContests not implemented")
}
func (UnimplementedProblemServiceServer) RandProblem(context.Context, *RandProblemRequest) (*RandProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandProblem not implemented")
}
func (UnimplementedProblemServiceServer) RawProblemList(context.Context, *RawProblemListRequest) (*RawProblemListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawProblemList not implemented")
}
func (UnimplementedProblemServiceServer) UpdateProblemGroup(context.Context, *UpdateProblemGroupRequest) (*UpdateProblemGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProblemGroup not implemented")
}
func (UnimplementedProblemServiceServer) mustEmbedUnimplementedProblemServiceServer() {}

// UnsafeProblemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProblemServiceServer will
// result in compilation errors.
type UnsafeProblemServiceServer interface {
	mustEmbedUnimplementedProblemServiceServer()
}

func RegisterProblemServiceServer(s grpc.ServiceRegistrar, srv ProblemServiceServer) {
	s.RegisterService(&_ProblemService_serviceDesc, srv)
}

func _ProblemService_ListProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProblemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).ListProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/ListProblems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).ListProblems(ctx, req.(*ListProblemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetProblemById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetProblemById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/GetProblemById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetProblemById(ctx, req.(*GetProblemByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_SearchProblemByCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProblemByConditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).SearchProblemByCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/SearchProblemByCondition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).SearchProblemByCondition(ctx, req.(*SearchProblemByConditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_CreateContest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).CreateContest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/CreateContest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).CreateContest(ctx, req.(*CreateContestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_ListContests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).ListContests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/ListContests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).ListContests(ctx, req.(*ListContestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_SearchContestByCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchContestByConditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).SearchContestByCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/SearchContestByCondition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).SearchContestByCondition(ctx, req.(*SearchContestByConditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetContestById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContestByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetContestById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/GetContestById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetContestById(ctx, req.(*GetContestByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_AddContestParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContestParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).AddContestParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/AddContestParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).AddContestParticipant(ctx, req.(*AddContestParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GenerateContestParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateContestParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GenerateContestParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/GenerateContestParticipants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GenerateContestParticipants(ctx, req.(*GenerateContestParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_AddContestAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContestAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).AddContestAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/AddContestAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).AddContestAdmin(ctx, req.(*AddContestAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetContestAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContestAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetContestAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/GetContestAdmins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetContestAdmins(ctx, req.(*GetContestAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetContestParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContestParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetContestParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/GetContestParticipants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetContestParticipants(ctx, req.(*GetContestParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_AddContestProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContestProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).AddContestProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/AddContestProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).AddContestProblem(ctx, req.(*AddContestProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_DeleteContestProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContestProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).DeleteContestProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/DeleteContestProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).DeleteContestProblem(ctx, req.(*DeleteContestProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_DeleteContestAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContestAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).DeleteContestAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/DeleteContestAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).DeleteContestAdmin(ctx, req.(*DeleteContestAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_UpdateContest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).UpdateContest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/UpdateContest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).UpdateContest(ctx, req.(*UpdateContestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_UpdateContestProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContestProblemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).UpdateContestProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/UpdateContestProblems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).UpdateContestProblems(ctx, req.(*UpdateContestProblemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetContestProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContestProblemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetContestProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/GetContestProblems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetContestProblems(ctx, req.(*GetContestProblemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetUserContests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserContestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetUserContests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/GetUserContests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetUserContests(ctx, req.(*GetUserContestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_RandProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).RandProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/RandProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).RandProblem(ctx, req.(*RandProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_RawProblemList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawProblemListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).RawProblemList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/RawProblemList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).RawProblemList(ctx, req.(*RawProblemListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_UpdateProblemGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProblemGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).UpdateProblemGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.ProblemService/UpdateProblemGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).UpdateProblemGroup(ctx, req.(*UpdateProblemGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProblemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sdk.ProblemService",
	HandlerType: (*ProblemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProblems",
			Handler:    _ProblemService_ListProblems_Handler,
		},
		{
			MethodName: "GetProblemById",
			Handler:    _ProblemService_GetProblemById_Handler,
		},
		{
			MethodName: "SearchProblemByCondition",
			Handler:    _ProblemService_SearchProblemByCondition_Handler,
		},
		{
			MethodName: "CreateContest",
			Handler:    _ProblemService_CreateContest_Handler,
		},
		{
			MethodName: "ListContests",
			Handler:    _ProblemService_ListContests_Handler,
		},
		{
			MethodName: "SearchContestByCondition",
			Handler:    _ProblemService_SearchContestByCondition_Handler,
		},
		{
			MethodName: "GetContestById",
			Handler:    _ProblemService_GetContestById_Handler,
		},
		{
			MethodName: "AddContestParticipant",
			Handler:    _ProblemService_AddContestParticipant_Handler,
		},
		{
			MethodName: "GenerateContestParticipants",
			Handler:    _ProblemService_GenerateContestParticipants_Handler,
		},
		{
			MethodName: "AddContestAdmin",
			Handler:    _ProblemService_AddContestAdmin_Handler,
		},
		{
			MethodName: "GetContestAdmins",
			Handler:    _ProblemService_GetContestAdmins_Handler,
		},
		{
			MethodName: "GetContestParticipants",
			Handler:    _ProblemService_GetContestParticipants_Handler,
		},
		{
			MethodName: "AddContestProblem",
			Handler:    _ProblemService_AddContestProblem_Handler,
		},
		{
			MethodName: "DeleteContestProblem",
			Handler:    _ProblemService_DeleteContestProblem_Handler,
		},
		{
			MethodName: "DeleteContestAdmin",
			Handler:    _ProblemService_DeleteContestAdmin_Handler,
		},
		{
			MethodName: "UpdateContest",
			Handler:    _ProblemService_UpdateContest_Handler,
		},
		{
			MethodName: "UpdateContestProblems",
			Handler:    _ProblemService_UpdateContestProblems_Handler,
		},
		{
			MethodName: "GetContestProblems",
			Handler:    _ProblemService_GetContestProblems_Handler,
		},
		{
			MethodName: "GetUserContests",
			Handler:    _ProblemService_GetUserContests_Handler,
		},
		{
			MethodName: "RandProblem",
			Handler:    _ProblemService_RandProblem_Handler,
		},
		{
			MethodName: "RawProblemList",
			Handler:    _ProblemService_RawProblemList_Handler,
		},
		{
			MethodName: "UpdateProblemGroup",
			Handler:    _ProblemService_UpdateProblemGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "problempb/service.proto",
}
