// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package crawlerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CrawlerServiceClient is the client API for CrawlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrawlerServiceClient interface {
	CrawlProblem(ctx context.Context, in *CrawlProblemRequest, opts ...grpc.CallOption) (*CrawlProblemResponse, error)
}

type crawlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlerServiceClient(cc grpc.ClientConnInterface) CrawlerServiceClient {
	return &crawlerServiceClient{cc}
}

func (c *crawlerServiceClient) CrawlProblem(ctx context.Context, in *CrawlProblemRequest, opts ...grpc.CallOption) (*CrawlProblemResponse, error) {
	out := new(CrawlProblemResponse)
	err := c.cc.Invoke(ctx, "/CrawlerService/CrawlProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerServiceServer is the server API for CrawlerService service.
// All implementations must embed UnimplementedCrawlerServiceServer
// for forward compatibility
type CrawlerServiceServer interface {
	CrawlProblem(context.Context, *CrawlProblemRequest) (*CrawlProblemResponse, error)
	mustEmbedUnimplementedCrawlerServiceServer()
}

// UnimplementedCrawlerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCrawlerServiceServer struct {
}

func (UnimplementedCrawlerServiceServer) CrawlProblem(context.Context, *CrawlProblemRequest) (*CrawlProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlProblem not implemented")
}
func (UnimplementedCrawlerServiceServer) mustEmbedUnimplementedCrawlerServiceServer() {}

// UnsafeCrawlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrawlerServiceServer will
// result in compilation errors.
type UnsafeCrawlerServiceServer interface {
	mustEmbedUnimplementedCrawlerServiceServer()
}

func RegisterCrawlerServiceServer(s grpc.ServiceRegistrar, srv CrawlerServiceServer) {
	s.RegisterService(&_CrawlerService_serviceDesc, srv)
}

func _CrawlerService_CrawlProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).CrawlProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CrawlerService/CrawlProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).CrawlProblem(ctx, req.(*CrawlProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CrawlerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CrawlerService",
	HandlerType: (*CrawlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlProblem",
			Handler:    _CrawlerService_CrawlProblem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawlerpb/service.proto",
}
